--- #YAML:1.0
name:               Eve
version:            0.05
abstract:           The web service creation framework written with events in mind.
author:
    - Igor Zinovyev <zinigor@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI::Session:         0
    Contextual::Return:   0
    DateTime:             0
    DateTime::Format::HTTP:  0
    DateTime::Format::Pg:  0
    DBD::Pg:              0
    Email::Sender::Simple:  0
    Exception::Class:     0
    Hash::MultiValue:     0
    JSON::XS:             0
    PadWalker:            0
    Plack::Request:       0
    Template:             0
    Test::Class:          0
    Test::MockObject:     0
    Test::More:           0
    Tie::IxHash:          0
    URI:                  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
